#!/usr/bin/php
<?php
/****
* This file is part of php-L2tpServer-server.
* Copyright (C) Sergei Lomakov <sergei@lomakov.net>
*
* php-L2tpServer-server is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* php-L2tpServer-server is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with php-L2tpServer-server.  If not, see <http://www.gnu.org/licenses/>.
*
*****/

define('L2TP_PHP_SERVER_VERSION', 0x00);
define('L2TP_PHP_SERVER_REVISION', 0x01);

error_reporting(E_ALL);
ini_set('display_errors', 'On');
date_default_timezone_set('Europe/Moscow');

require_once('vendor/autoload.php');

use L2tpServer\General\Server as L2TPServer;

$l2tp_server = new L2TPServer();
$l2tp_server->run();
